# Generated by Django 3.2.25 on 2024-05-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
